name: Luan Porfirio e Silva
bio: Drinking one coffee at a time
description: A blog about technology and stuff related
external-image: false
picture: assets/images/luan_avatar.png
resume: true
resume-external: true
resume-url: 'https://google.com/?q=my+resume'
url: 'https://luanps.github.io'
permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories:
    - blog
    - project
github: luanps
linkedin: luan-porfirio-3961b5141
instagram: lopes_porfirio
facebook: 100009379809445
email: luann.porfirio@gmail.com
authors:
  johndoe:
    name: John Doe'
    bio: A Man who travels the world eating noodles
    external-image: false
    picture: assets/images/profile.jpg
    twitter: johndoe
  jamesfoster:
    name: James Foster
    bio: A Man who develops software with coffee
    external-image: false
    picture: assets/images/james.jpg
    twitter: jamesfoster
width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
